apiVersion: v1 
kind: Service
metadata: 
  name: elasticsearch
  namespace: logging
spec: 
  type: ClusterIP
  ports: 
    - port: 9200
      name: http
  selector: 
    app: elasticsearch

---

apiVersion: apps/v1
kind: StatefulSet 
metadata: 
  name: elasticsearch
  namespace: logging 
spec: 
  serviceName: elasticsearch
  replicas: 1 
  selector:
    matchLabels: 
      app: elasticsearch
  template: 
    metadata:
      labels: 
        app: elasticsearch
    spec: 
      containers: 
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
        ports: 
          - containerPort: 9200
            name: http
        env: 
          - name: discovery.type
            value: single-node
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"
          - name: xpack.security.enabled
            value: "false"
        resources: 
          requests: 
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 1 
            memory: 1Gi
        volumeMounts:
          - name: es-data
            mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
    - metadata: 
        name: es-data
      spec: 
        accessModes: ["ReadWriteOnce"]
        resources: 
          requests:
            storage: 5Gi