apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
  namespace: nginx-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
        - name: nginx-demo
          image: 192.168.1.70:30500/our-task/nginx-demo:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-demo-svc
  namespace: nginx-demo
spec:
  type: LoadBalancer
  selector:
    app: nginx-demo
  loadBalancerIP: 192.168.1.204
  ports:
    - name: http
      port: 80
      targetPort: 80
